<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\OctopusEnergyDashboard.Application\OctopusEnergyDashboard.Application.csproj" />
    <ProjectReference Include="..\OctopusEnergyDashboard.Infrastructure\OctopusEnergyDashboard.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
